version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 80:8080
  db:
    image: postgres:12
    env_file:
      - ./config/db.env
  auth_db:
    image: redis
  express-app:
    build: express-app/.
    volumes:
      - ./express-app/:/usr/local/express
