version: "3"
services:
  db:
    image: postgres:12
    env_file:
      - ./config/db.env
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d/
  user-subscriber:
    build: user-subscriber/.
    volumes:
      - ./user-subscriber/:/go/src/app
    depends_on:
      - db
  express-app:
    build: express-app/.
    volumes:
      - ./express-app/:/usr/local/express
    links:
      - db
    depends_on:
      - user-subscriber
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 80:8080
    depends_on:
      - express-app
  # rabbitmq:
  #   image: rabbitmq:management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  # auth_db:
  #   image: redis
